version: '3.9'

services:
  mongo:
    env_file:
      - stack.env
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - 'mongo_data:/data/db'
      - 'mongo_config:/data/configdb'
    networks:
      - default
  discord: &common
    image: andrempcosta/bot-repo:latest
    container_name: discord-worker
    command: pipenv run bot
    env_file:
      - stack.env
    volumes:
      - "bot_data:/DiscordMatchmaker/data:rw"
    networks:
      - default
  webapp:
    <<: *common
    env_file:
      - stack.env
    container_name: webapp
    command: pipenv run webapp
    ports:
      - "16000:16000"
    networks:
      - default
volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local
  bot_data:
    driver: local
networks:
  default:
    name: default-network
    external: true